### ISSUE TITLE
Develop Ethernet Code for Rev3

### ISSUE THREAD

**Issue by Kwuerch** [CalPolyRobotics/IGVC-OlympusFirmware#46]
Develop the Ethernet code for Revision 3, which will be using a stm32f207ZGT6U.

**Comment by evanash16** [comment]
I just pushed a change to this branch which converts the tcp_echoserver_recv function to a function which utilizes the runCommsFSM function to handle messages sent over ethernet. The test script, eth_client.py, attempts to use the 0x00 message type to get an echoed response but this doesn't appear to work too well. I'm fairly certain it's close though.

**Comment by ssmarok** [comment]
Closed via merge into master.
