### ISSUE TITLE
Steering Motor Low Level Driver

### ISSUE THREAD

**Issue by Kwuerch** [CalPolyRobotics/IGVC-OlympusFirmware#65]
Needs pwm timer output instead of V2 GPIO writes

**Comment by Kwuerch** [comment]
This is now ready to test. The low-level driver was integrated with the existing bang-bang driver.

Note the following needed to finessed/verified:
* tim1_duty_lut values
* tim1 output frequency (defined by ARR_20KHZ)
* actual steering direction output from board

**Comment by ssmarok** [comment]
Closed via merge into master.
