### ISSUE TITLE
Transfer hall-effect sensor code from main microcontroller

### ISSUE THREAD

**Issue by Kwuerch** [CalPolyRobotics/IGVC-OlympusFirmware#9]
Use the original hall effect sensor code as a basis for the new code on the Hera M0. A function needs to be implemented that can be called and will return the speed of either the right or left wheel in (mm/s)

**Comment by evanash16** [comment]
Added commit to I9 branch adding the base GPIO init stuff for the Hall-Effect sensors on Hera. I am currently reading into the TIM2 general purpose timer to understand what signals/pins I need to focus on.
